### ISSUE TITLE
Find good PLS References

### ISSUE THREAD

**Issue by DawningAventide** [sds-capstone/PLSmodel#17]
@beanumber, finding papers or other resources to better understand the model being used.

**Comment by beanumber** [comment]
1. I always like to start with something more general. The [Wikipedia entry](https://en.wikipedia.org/wiki/Partial_least_squares_regression) provides a nice orientation. 
2. [This article](https://towardsdatascience.com/partial-least-squares-f4e6714452a) was also helpful, and it includes R code that walks you through actually computing a PLS model. 
3. [This treatment](https://personal.utdallas.edu/~herve/Abdi-PLS-pretty.pdf) is more mathematical, but it feels like a more authoritative, grad school textbook treatment. 
4. If you choose to use `tidymodels`, [here](https://www.tidymodels.org/learn/models/pls/) is a tutorial on computing in that paradigm.
