### ISSUE TITLE
Figure out where to automate the process using functions

### ISSUE THREAD

**Issue by hartlegr** [sds-capstone/PLSmodel#23]
As a user I want to be able to feed my dataset into this model, so I want to have functions that are semi-universal to clean my data and get into the format needed. As a data scientist, I want to figure out ahead of time where these functions would be most useful so that I can implement them with ease in sprint 3. 

This item is done when a .txt file exists in the repo with a list of functions we want to add, as well as comments inline mentioning where the function will be and what it will do.

**Comment by hartlegr** [comment]
This feels a little ~abstract~ in terms of being "done"...any suggestions? @ranawg @LyraDusk

**Comment by ranawg** [comment]
I feel that documenting the functions in README should be a different issue than identifying and writing each function. so maybe this one is done when we have a commented line on identified positions?
